name: Java CD with Gradle

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  deploy:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/배포') && contains(github.event.comment.body, '배포')
    runs-on: ubuntu-latest
    permissions:
      write-all


    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./infra/docker/Dockerfile \
            -t ${{ secrets.DOCKER_REPO }}:latest \
            --push \
            .

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop ElevenBE
            sudo docker rm ElevenBE
            sudo docker rmi ${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker run -d --name ElevenBE -p 9000:9000 ${{ secrets.DOCKER_REPO }}

      - name: Notify
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🌎 배포하였습니다.'
            })

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ":satellite: 자동 배포"